### ISSUE TITLE
ValueExtractor assumes ordered existence of cellsize and tickrate although optional

### ISSUE THREAD

**Issue by falkecarlsen** [d409f19/cellmata#71]
Passing the Cellmata program:
```kotlin
world {
    size = 100 [wrap], 200 [wrap]
}

state ident (0, 0, 0) {
    become ident;
}
```

Throws an NPE:
```java
java.lang.NullPointerException
	at dk.aau.cs.d409f19.cellumata.visitors.LiteralExtractorVisitor.visit(valueextractor.kt:201)
	at dk.aau.cs.d409f19.cellumata.visitors.BaseASTVisitor.visit(visitor.kt:125)
	at dk.aau.cs.d409f19.cellumata.visitors.BaseASTVisitor.visit(visitor.kt:103)
	at dk.aau.cs.d409f19.Utilities$Companion.compileProgram(utility.kt:29)
	at dk.aau.cs.d409f19.BatchTest.batchPass(batchtest.kt:16)
```

**Comment by falkecarlsen** [comment]
Also, order is limited to `tickrate` then `cellsize`, in grammar as shown with the following error-msg: `line 4:4 mismatched input 'tickrate' expecting '}'` on input:
```kotlin
world {
    size = 100 [wrap], 200 [wrap]
    cellsize = 5
    tickrate = 1
}

state ident (0, 0, 0) {
    become ident;
}
```
